const GP = Object.freeze({
  VERSION: '2.3.1-REAL-WORLD',
  NAME: 'GRAFIK PRO DEMO 2.3.1',
  TZ: 'Europe/Warsaw',
  LOCALE: 'pl_PL',
  SHEETS: {
    CONFIG: 'CONFIG',
    USERS: 'UŻYTKOWNICY',
    EMPLOYEES: 'PRACOWNICY',
    CONTRACTS: 'ZATRUDNIENIE',
    LOCATIONS: 'LOKALIZACJE',
    SHIFT_TYPES: 'TYPY_ZMIAN',
    DEMAND: 'ZAPOTRZEBOWANIE',
    AVAILABILITY: 'DOSTĘPNOŚĆ',
    ABSENCES: 'NIEOBECNOŚCI',
    EVENTS: 'WYDARZENIA',
    PLANS: 'PLANY',
    ASSIGNMENTS: 'PRZYDZIAŁY',
    VERSIONS: 'WERSJE_PLANU',
    BUDGETS: 'BUDŻETY',
    COSTS: 'KOSZTY_CHRONIONE',
    SWAPS: 'ZAMIANY',
    NOTIFICATIONS: 'POWIADOMIENIA',
    AUDIT: 'AUDYT',
    KPI: 'KPI',
    IMPORT: 'IMPORT_KADROMIERZ',
    EXPORT: 'EKSPORT_KADROMIERZ',
    BACKUPS: 'KOPIE_ZAPASOWE',
    TESTS: 'TESTY'
    ,CENTRALS: 'CENTRALE'
    ,SCENARIOS: 'SCENARIUSZE'
    ,MODES: 'TRYBY_OPTYMALIZACJI'
    ,LEVELS: 'POZIOMY_OBSADY'
    ,SHIFT_DEFINITIONS: 'DEFINICJE_ZMIAN'
    ,STAFFING_MATRIX: 'MACIERZ_OBSADY'
    ,DAY_EXCEPTIONS: 'WYJĄTKI_DNI'
    ,EXTRA_FUNCTIONS: 'FUNKCJE_DODATKOWE'
    ,ROLE_PLANS: 'GRAFIKI_ROLOWE'
    ,EMERGENCY: 'ZMIANY_AWARYJNE'
  },
  ROLES: {
    ADMIN: 'ADMIN',
    ACCOUNTING: 'KSIĘGOWOŚĆ',
    MANAGER: 'KIEROWNIK',
    EMPLOYEE: 'PRACOWNIK',
    DEMO: 'DEMO'
  },
  PLAN_STATUS: {
    DRAFT: 'ROBOCZY',
    VALIDATED: 'ZWERYFIKOWANY',
    PUBLISHED: 'OPUBLIKOWANY',
    ARCHIVED: 'ARCHIWALNY'
  },
  ASSIGNMENT_STATUS: {
    PLANNED: 'ZAPLANOWANA',
    CONFIRMED: 'POTWIERDZONA',
    SWAP_PENDING: 'ZAMIANA_OCZEKUJE',
    CANCELLED: 'ANULOWANA'
  },
  DEFAULTS: {
    MIN_REST_HOURS: 11,
    MAX_CONSECUTIVE_DAYS: 6,
    MAX_WEEKLY_HOURS: 48,
    MINUTES_PER_SLOT: 15,
    STANDBY_PER_LOCATION: 1,
    FAIRNESS_WEIGHT: 22,
    PREFERENCE_WEIGHT: 14,
    COST_WEIGHT: 18,
    CONTINUITY_WEIGHT: 8,
    UNDERSTAFF_WEIGHT: 1000,
    HARD_VIOLATION_WEIGHT: 100000
  }
});

const GP_HEADERS = Object.freeze({
  [GP.SHEETS.CONFIG]: ['KLUCZ', 'WARTOŚĆ', 'OPIS', 'EDYTOWALNE'],
  [GP.SHEETS.USERS]: ['EMAIL', 'ROLA', 'PRACOWNIK_ID', 'LOKALIZACJE', 'AKTYWNY'],
  [GP.SHEETS.EMPLOYEES]: ['ID', 'IMIĘ_I_NAZWISKO', 'EMAIL', 'TELEFON', 'AKTYWNY', 'ROLA_GŁÓWNA', 'LOKALIZACJA_BAZOWA', 'KRUCZA_STANDARD', 'PAWILONY_STANDARD', 'KRUCZA_NADGODZINY', 'PAWILONY_NADGODZINY', 'HOST', 'ZAMKNIĘCIE_BARU', 'ZAMKNIĘCIE_SALI', 'MENADŻER_ZESPOŁU', 'ZARZĄDZA_ROLĄ', 'ZARZĄDZA_LOKALIZACJĄ', 'ROTACYJNY', 'SPLIT_SHIFT', 'EVENT', 'STANDBY', 'PRIORYTET'],
  [GP.SHEETS.CONTRACTS]: ['PRACOWNIK_ID', 'TYP_UMOWY', 'ETAT', 'GODZINY_MIESIĘCZNE', 'STAWKA_GODZINOWA', 'KOSZT_PRACODAWCY_H', 'OD', 'DO', 'TYLKO_RANO', 'DOZWOLONE_LOKALIZACJE', 'MAX_DNI_Z_RZĘDU', 'MAX_H_TYDZIEŃ', 'TYLKO_POPOŁUDNIE', 'BEZ_WEEKENDÓW', 'DOSTĘPNY_STANDBY', 'MIN_ODPOCZYNEK_H'],
  [GP.SHEETS.LOCATIONS]: ['ID', 'NAZWA', 'ADRES', 'AKTYWNA', 'KIEROWNIK_EMAIL', 'KOLOR'],
  [GP.SHEETS.SHIFT_TYPES]: ['ID', 'NAZWA', 'START', 'KONIEC', 'KONIEC_DZIEŃ_PLUS', 'PŁATNE_H', 'TYP', 'KOLOR'],
  [GP.SHEETS.DEMAND]: ['DATA', 'LOKALIZACJA_ID', 'ZMIANA_ID', 'ROLA', 'FUNKCJA_WYMAGANA', 'MIN_OSÓB', 'OPTYMALNIE_OSÓB', 'MAX_OSÓB', 'STANDBY', 'PRIORYTET', 'ŹRÓDŁO'],
  [GP.SHEETS.AVAILABILITY]: ['PRACOWNIK_ID', 'DATA', 'OD', 'DO', 'STATUS', 'PREFERENCJA', 'LOKALIZACJA_ID', 'UWAGI'],
  [GP.SHEETS.ABSENCES]: ['ID', 'PRACOWNIK_ID', 'OD', 'DO', 'TYP', 'STATUS', 'ŹRÓDŁO', 'UWAGI'],
  [GP.SHEETS.EVENTS]: ['ID', 'NAZWA', 'OD', 'DO', 'LOKALIZACJA_ID', 'ZMIANA_ID', 'ROLA', 'DODATKOWE_OSOBY', 'START_OVERRIDE', 'KONIEC_OVERRIDE', 'DODATKOWA_ZMIANA', 'UWAGI'],
  [GP.SHEETS.PLANS]: ['ID', 'NAZWA', 'MIESIĄC', 'SCENARIUSZ', 'TRYB', 'STATUS', 'UTWORZYŁ', 'UTWORZONO', 'WYNIK', 'KOSZT', 'UWAGI'],
  [GP.SHEETS.ASSIGNMENTS]: ['ID', 'PLAN_ID', 'DATA', 'LOKALIZACJA_ID', 'ZMIANA_ID', 'OD', 'DO', 'DZIEŃ_PLUS', 'PRACOWNIK_ID', 'ROLA', 'FUNKCJA', 'KLASYFIKACJA', 'STANDBY', 'STATUS', 'KOSZT', 'ŹRÓDŁO', 'UWAGI'],
  [GP.SHEETS.VERSIONS]: ['ID', 'PLAN_ID', 'WERSJA', 'UTWORZYŁ', 'UTWORZONO', 'POWÓD', 'SNAPSHOT_JSON'],
  [GP.SHEETS.BUDGETS]: ['MIESIĄC', 'LOKALIZACJA_ID', 'BUDŻET', 'LIMIT_H', 'OSTRZEŻENIE_PROC', 'AKTYWNY'],
  [GP.SHEETS.COSTS]: ['PRACOWNIK_ID', 'MIESIĄC', 'STAWKA_H', 'DODATEK_NOCNY', 'DODATEK_WEEKEND', 'KOSZT_STAŁY', 'UWAGI'],
  [GP.SHEETS.SWAPS]: ['ID', 'PRZYDZIAŁ_ID', 'OD_PRACOWNIKA_ID', 'DO_PRACOWNIKA_ID', 'STATUS', 'UTWORZONO', 'ZATWIERDZIŁ', 'UWAGI'],
  [GP.SHEETS.NOTIFICATIONS]: ['ID', 'ODBIORCA', 'TYP', 'TYTUŁ', 'TREŚĆ', 'STATUS', 'UTWORZONO', 'WYSŁANO'],
  [GP.SHEETS.AUDIT]: ['CZAS', 'UŻYTKOWNIK', 'AKCJA', 'ENCJA', 'ENCJA_ID', 'PRZED', 'PO', 'KORELACJA_ID'],
  [GP.SHEETS.KPI]: ['PLAN_ID', 'METRYKA', 'WARTOŚĆ', 'CEL', 'STATUS', 'OPIS'],
  [GP.SHEETS.IMPORT]: ['STATUS', 'TYP', 'WIERSZ_ŹRÓDŁOWY', 'PRACOWNIK', 'OD', 'DO', 'UWAGI'],
  [GP.SHEETS.EXPORT]: ['PRACOWNIK', 'DATA', 'OD', 'DO', 'LOKALIZACJA', 'TYP_ZMIANY', 'UWAGI'],
  [GP.SHEETS.BACKUPS]: ['ID', 'UTWORZONO', 'UTWORZYŁ', 'TYP', 'OPIS', 'PLIK_ID'],
  [GP.SHEETS.TESTS]: ['CZAS', 'TEST', 'STATUS', 'SZCZEGÓŁY']
  ,[GP.SHEETS.CENTRALS]: ['KLUCZ', 'WARTOŚĆ', 'OPIS', 'STATUS']
  ,[GP.SHEETS.SCENARIOS]: ['SCENARIUSZ_ID', 'NAZWA', 'MNOŻNIK_ZAPOTRZEBOWANIA', 'MNOŻNIK_BUDŻETU', 'DOMYŚLNY_POZIOM_OBSADY', 'NADGODZINY', 'MAX_NADGODZIN_H', 'REDUKCJA_DOSTĘPNOŚCI_PROC', 'ZATRUDNIENIE_CZASOWE', 'AKTYWNY', 'OPIS']
  ,[GP.SHEETS.MODES]: ['TRYB_ID', 'NAZWA', 'WAGA_KOSZT_PROC', 'WAGA_PREFERENCJE_PROC', 'WAGA_SPRAWIEDLIWOŚĆ_PROC', 'WAGA_POKRYCIE_PROC', 'WAGA_CIĄGŁOŚĆ_PROC', 'AKTYWNY', 'OPIS']
  ,[GP.SHEETS.LEVELS]: ['POZIOM_ID', 'NAZWA', 'ŹRÓDŁO_CELU', 'MNOŻNIK', 'LIMIT_BUDŻETU_PROC', 'AKTYWNY', 'OPIS']
  ,[GP.SHEETS.SHIFT_DEFINITIONS]: ['LOKALIZACJA_ID','GRUPA_DNI','DZIEŃ_TYGODNIA','ZMIANA_ID','NAZWA','START','KONIEC','KONIEC_DZIEŃ_PLUS','AKTYWNA']
  ,[GP.SHEETS.STAFFING_MATRIX]: ['LOKALIZACJA_ID','GRUPA_DNI','ZMIANA_ID','ROLA','FUNKCJA_WYMAGANA','MIN_OSÓB','OPTYMALNIE_OSÓB','MAX_OSÓB','AKTYWNA']
  ,[GP.SHEETS.DAY_EXCEPTIONS]: ['ID','DATA','LOKALIZACJA_ID','TYP','ZMIANA_ID','ROLA','WARTOŚĆ','START','KONIEC','DZIEŃ_PLUS','NAZWA','UWAGI','AKTYWNY']
  ,[GP.SHEETS.EXTRA_FUNCTIONS]: ['KOD','NAZWA','ROLA_WYMAGANA','LOKALIZACJA','TYP_PRZYDZIAŁU','AKTYWNA','OPIS']
  ,[GP.SHEETS.ROLE_PLANS]: ['PLAN_ID','ROLA','STATUS','MENADŻEROWIE','LICZBA_PRZYDZIAŁÓW','BRAKI','KOSZT','OSTATNIA_AKTUALIZACJA']
  ,[GP.SHEETS.EMERGENCY]: ['ID','PLAN_ID','DATA','LOKALIZACJA_ID','ZMIANA_ID','ROLA','NIEOBECNY_ID','ZASTĘPCA_ID','STATUS','POWIADOMIĆ','KANAŁ','UTWORZYŁ','UTWORZONO','UWAGI']
});

function gpSs_() {
  const ss = SpreadsheetApp.getActive();
  if (!ss) throw new Error('Aplikacja musi być powiązana z Arkuszem Google.');
  return ss;
}

function gpId_(prefix) {
  return `${prefix}-${Utilities.getUuid().slice(0, 8).toUpperCase()}`;
}

function gpNow_() {
  return Utilities.formatDate(new Date(), GP.TZ, "yyyy-MM-dd'T'HH:mm:ss");
}

function gpMonth_(value) {
  const d = value instanceof Date ? value : new Date(`${String(value).slice(0, 7)}-01T12:00:00`);
  if (isNaN(d)) throw new Error('Nieprawidłowy miesiąc.');
  return Utilities.formatDate(d, GP.TZ, 'yyyy-MM');
}

function gpDate_(value) {
  const d = value instanceof Date ? value : new Date(value);
  if (isNaN(d)) throw new Error(`Nieprawidłowa data: ${value}`);
  return Utilities.formatDate(d, GP.TZ, 'yyyy-MM-dd');
}
